package ${project.packageName}.extend.service;

import ${project.packageName}.standard.model.${entity.name};
import ${project.packageName}.standard.service.${entity.name}Service;

/**
* Generated By BatMan on ${.now}
*/
public interface ${entity.name}ExtendService extends ${entity.name}Service{

}

/**
* Generated By BatMan on ${.now}
*/