package ${project.packageName}.extend.repository;

import ${project.packageName}.standard.model.${entity.name};
import ${project.packageName}.standard.repository.${entity.name}Repository;
import org.springframework.stereotype.Repository;
/**
* Generated By BatMan on ${.now}
*/
@Repository
public interface ${entity.name}ExtendRepository extends ${entity.name}Repository {
}

/**
* Generated By BatMan on ${.now}
*/