package ${project.packageName}.standard.repository;

import ${project.packageName}.standard.model.${entity.name};
import com.rayleigh.core.customQuery.CustomRepository;

/**
* Generated By BatMan on ${.now}
*/
public interface ${entity.name}Repository extends CustomRepository<${entity.name}, String> {
}

/**
* Generated By BatMan on ${.now}
*/